version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

build_script:
  gradlew.bat build --info --no-daemon

test_script:
  gradlew.bat test compileSlowtest datatest pfinttest --info --no-daemon

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

matrix:
  fast_finish: true

cache:
  - C:\Users\appveyor\.gradle
