/*
 * NetworkView.java
 *
 * Created on April 22, 2004, 1:54 PM
 */

package plugin.network.gui;

/**
 *
 * @author  ddjone3
 */
public class NetworkView extends javax.swing.JPanel
{

	/** Creates new form NetworkView */
	public NetworkView()
	{
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents()
	{//GEN-BEGIN:initComponents
		buttonGroup1 = new javax.swing.ButtonGroup();
		toolbar = new javax.swing.JToolBar();
		rbServer = new javax.swing.JRadioButton();
		rbClient = new javax.swing.JRadioButton();
		clientPanel = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		serverAddress = new javax.swing.JTextField();
		connectButton = new javax.swing.JButton();
		localPanel = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		localAddress = new javax.swing.JLabel();
		connectionPanel = new javax.swing.JPanel();
		noteTitle = new javax.swing.JLabel();
		noteText = new javax.swing.JLabel();
		logPane = new javax.swing.JTabbedPane();
		messagePanel = new javax.swing.JPanel();
		messageBox = new javax.swing.JTextField();
		messageButton = new javax.swing.JButton();
		connectedUsersPanel = new javax.swing.JPanel();
		userList = new javax.swing.JList();
		jLabel1 = new javax.swing.JLabel();

		setLayout(new java.awt.BorderLayout());

		rbServer.setText("Server");
		buttonGroup1.add(rbServer);
		toolbar.add(rbServer);

		rbClient.setText("Client");
		buttonGroup1.add(rbClient);
		toolbar.add(rbClient);

		clientPanel.setLayout(new java.awt.FlowLayout(
			java.awt.FlowLayout.CENTER, 5, 3));

		jLabel2.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
		jLabel2.setText("Server Address: ");
		clientPanel.add(jLabel2);

		serverAddress.setText("0.0.0.0");
		serverAddress.setMinimumSize(new java.awt.Dimension(50, 20));
		serverAddress.setPreferredSize(new java.awt.Dimension(100, 20));
		clientPanel.add(serverAddress);

		connectButton.setText("Connect");
		connectButton.setMargin(new java.awt.Insets(0, 10, 0, 10));
		clientPanel.add(connectButton);

		toolbar.add(clientPanel);

		localPanel.setLayout(new java.awt.FlowLayout(
			java.awt.FlowLayout.CENTER, 5, 6));

		jLabel3.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
		jLabel3.setText("Local Address:");
		localPanel.add(jLabel3);

		localAddress.setFont(new java.awt.Font("Dialog", 0, 12));
		localAddress.setText("0.0.0.0");
		localPanel.add(localAddress);

		toolbar.add(localPanel);

		connectionPanel.setLayout(new java.awt.FlowLayout(
			java.awt.FlowLayout.CENTER, 5, 6));

		connectionPanel.add(noteTitle);

		noteText.setFont(new java.awt.Font("Dialog", 0, 12));
		connectionPanel.add(noteText);

		toolbar.add(connectionPanel);

		add(toolbar, java.awt.BorderLayout.NORTH);

		add(logPane, java.awt.BorderLayout.CENTER);

		messagePanel.setLayout(new java.awt.BorderLayout());

		messagePanel.add(messageBox, java.awt.BorderLayout.CENTER);

		messageButton.setText("Send Message");
		messagePanel.add(messageButton, java.awt.BorderLayout.EAST);

		add(messagePanel, java.awt.BorderLayout.SOUTH);

		connectedUsersPanel.setLayout(new java.awt.BorderLayout());

		connectedUsersPanel.setBorder(new javax.swing.border.EtchedBorder());
		userList.setBorder(new javax.swing.border.EtchedBorder());
		userList.setModel(new javax.swing.AbstractListModel()
		{
			String[] strings = {"Broadcast"};

			public int getSize()
			{
				return strings.length;
			}

			public Object getElementAt(int i)
			{
				return strings[i];
			}
		});
		userList
			.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		connectedUsersPanel.add(userList, java.awt.BorderLayout.CENTER);

		jLabel1.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
		jLabel1.setText(" Network: ");
		connectedUsersPanel.add(jLabel1, java.awt.BorderLayout.NORTH);

		add(connectedUsersPanel, java.awt.BorderLayout.EAST);

	}//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.JPanel clientPanel;
	private javax.swing.JButton connectButton;
	private javax.swing.JPanel connectedUsersPanel;
	private javax.swing.JPanel connectionPanel;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel localAddress;
	private javax.swing.JPanel localPanel;
	private javax.swing.JTabbedPane logPane;
	private javax.swing.JTextField messageBox;
	private javax.swing.JButton messageButton;
	private javax.swing.JPanel messagePanel;
	private javax.swing.JLabel noteText;
	private javax.swing.JLabel noteTitle;
	private javax.swing.JRadioButton rbClient;
	private javax.swing.JRadioButton rbServer;
	private javax.swing.JTextField serverAddress;
	private javax.swing.JToolBar toolbar;
	private javax.swing.JList userList;

	// End of variables declaration//GEN-END:variables

	public javax.swing.JTabbedPane getLogPane()
	{
		return logPane;
	}

	public javax.swing.JTextField getServerAddressTextField()
	{
		return serverAddress;
	}

	public javax.swing.JButton getConnectButton()
	{
		return connectButton;
	}

	public javax.swing.JRadioButton getServerRadioButton()
	{
		return rbServer;
	}

	public javax.swing.JRadioButton getClientRadioButton()
	{
		return rbClient;
	}

	public javax.swing.JButton getMessageButton()
	{
		return messageButton;
	}

	public javax.swing.JTextField getMessageTextField()
	{
		return messageBox;
	}

	public javax.swing.JList getUserList()
	{
		return userList;
	}

	public void setLocalAddressText(String address)
	{
		localAddress.setText(address);
	}

	public void setConnectionText(String title, String text)
	{
		noteTitle.setText(title + ":");
		noteText.setText(text);
	}

	public void hideClientPanel()
	{
		clientPanel.setVisible(false);
	}

	public void showClientPanel()
	{
		clientPanel.setVisible(true);
	}

	public void hideConnectionPanel()
	{
		connectionPanel.setVisible(false);
	}

	public void showConnectionPanel()
	{
		connectionPanel.setVisible(true);
	}

	public void hideLocalPanel()
	{
		localPanel.setVisible(false);
	}

	public void showLocalPanel()
	{
		localPanel.setVisible(true);
	}
}
