/* Generated By:JJTree: Do not edit this line. ASTPCGenSingleWord.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package pcgen.base.formula.parse;

public
class ASTPCGenSingleWord extends SimpleNode {
  public ASTPCGenSingleWord(int id) {
    super(id);
  }

  public ASTPCGenSingleWord(FormulaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FormulaParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d626bc36cd2aa53587e1116d6ff6df64 (do not edit this line) */
