/* Generated By:JavaCC: Do not edit this line. FormulaParserDefaultVisitor.java Version 7.0.13 */
package pcgen.base.formula.parse;

public class FormulaParserDefaultVisitor implements FormulaParserVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTRoot node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLogical node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTEquality node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTRelational node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTArithmetic node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTGeometric node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTUnaryMinus node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTUnaryNot node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExpon node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTParen node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTNum node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTPCGenLookup node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTPCGenSingleWord node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTPCGenBracket node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFParen node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTQuotString node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=ef6ff0786bb1f3018972ad2d72bd2057 (do not edit this line) */
