/* Generated By:JavaCC: Do not edit this line. FormulaParserVisitor.java Version 7.0.13 */
package pcgen.base.formula.parse;

public interface FormulaParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTRoot node, Object data);
  public Object visit(ASTLogical node, Object data);
  public Object visit(ASTEquality node, Object data);
  public Object visit(ASTRelational node, Object data);
  public Object visit(ASTArithmetic node, Object data);
  public Object visit(ASTGeometric node, Object data);
  public Object visit(ASTUnaryMinus node, Object data);
  public Object visit(ASTUnaryNot node, Object data);
  public Object visit(ASTExpon node, Object data);
  public Object visit(ASTParen node, Object data);
  public Object visit(ASTNum node, Object data);
  public Object visit(ASTPCGenLookup node, Object data);
  public Object visit(ASTPCGenSingleWord node, Object data);
  public Object visit(ASTPCGenBracket node, Object data);
  public Object visit(ASTFParen node, Object data);
  public Object visit(ASTQuotString node, Object data);
}
/* JavaCC - OriginalChecksum=d380ad9d2317a3447548ec484828a7ff (do not edit this line) */
