/* Generated By:JavaCC: Do not edit this line. FormulaParserTreeConstants.java Version 7.0.13 */
package pcgen.base.formula.parse;

public interface FormulaParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTVOID = 1;
  public int JJTLOGICAL = 2;
  public int JJTEQUALITY = 3;
  public int JJTRELATIONAL = 4;
  public int JJTARITHMETIC = 5;
  public int JJTGEOMETRIC = 6;
  public int JJTUNARYMINUS = 7;
  public int JJTUNARYNOT = 8;
  public int JJTEXPON = 9;
  public int JJTPAREN = 10;
  public int JJTNUM = 11;
  public int JJTPCGENLOOKUP = 12;
  public int JJTPCGENSINGLEWORD = 13;
  public int JJTPCGENBRACKET = 14;
  public int JJTFPAREN = 15;
  public int JJTQUOTSTRING = 16;


  public String[] jjtNodeName = {
    "Root",
    "void",
    "Logical",
    "Equality",
    "Relational",
    "Arithmetic",
    "Geometric",
    "UnaryMinus",
    "UnaryNot",
    "Expon",
    "Paren",
    "Num",
    "PCGenLookup",
    "PCGenSingleWord",
    "PCGenBracket",
    "FParen",
    "QuotString",
  };
}
/* JavaCC - OriginalChecksum=b6023e47faca655aaa5937d5713ac8bb (do not edit this line) */
