/*
 * DetailsPane.java
 *
 * Created on February 2, 2004, 9:23 PM
 */

package plugin.charactersheet.gui;

import gmgen.plugin.PlayerCharacterOutput;
import pcgen.core.Constants;
import pcgen.core.PCClass;
import pcgen.core.PlayerCharacter;
import pcgen.io.exporttoken.AlignmentToken;
import pcgen.io.exporttoken.HeightToken;
import pcgen.io.exporttoken.SizeLongToken;
import pcgen.io.exporttoken.WeightToken;

import java.util.ArrayList;

/**
 * Confirmed no memory Leaks Dec 10, 2004
 * @author  soulcatcher
 */
public class DetailsPane extends javax.swing.JPanel {
	private PlayerCharacter pc;

	/** Creates new form DetailsPane */
	public DetailsPane() {
		initComponents();
		setColor();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents() {//GEN-BEGIN:initComponents
		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jPanel5 = new javax.swing.JPanel();
		jPanel21 = new javax.swing.JPanel();
		name = new javax.swing.JLabel();
		jSeparator19 = new javax.swing.JSeparator();
		jPanel22 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jPanel6 = new javax.swing.JPanel();
		jPanel7 = new javax.swing.JPanel();
		jPanel32 = new javax.swing.JPanel();
		playerClass = new javax.swing.JLabel();
		jSeparator20 = new javax.swing.JSeparator();
		jPanel29 = new javax.swing.JPanel();
		jLabel20 = new javax.swing.JLabel();
		jPanel30 = new javax.swing.JPanel();
		characterLevel = new javax.swing.JLabel();
		jSeparator21 = new javax.swing.JSeparator();
		jPanel31 = new javax.swing.JPanel();
		jLabel21 = new javax.swing.JLabel();
		jPanel8 = new javax.swing.JPanel();
		jPanel36 = new javax.swing.JPanel();
		experience = new javax.swing.JLabel();
		jSeparator22 = new javax.swing.JSeparator();
		jPanel34 = new javax.swing.JPanel();
		jLabel22 = new javax.swing.JLabel();
		jPanel35 = new javax.swing.JPanel();
		nextLevel = new javax.swing.JLabel();
		jSeparator23 = new javax.swing.JSeparator();
		jPanel33 = new javax.swing.JPanel();
		jLabel23 = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		jPanel9 = new javax.swing.JPanel();
		jPanel23 = new javax.swing.JPanel();
		playerName = new javax.swing.JLabel();
		jSeparator29 = new javax.swing.JSeparator();
		jPanel24 = new javax.swing.JPanel();
		jLabel24 = new javax.swing.JLabel();
		jPanel10 = new javax.swing.JPanel();
		jPanel11 = new javax.swing.JPanel();
		jPanel40 = new javax.swing.JPanel();
		race = new javax.swing.JLabel();
		jSeparator25 = new javax.swing.JSeparator();
		jPanel39 = new javax.swing.JPanel();
		jLabel25 = new javax.swing.JLabel();
		jPanel37 = new javax.swing.JPanel();
		age = new javax.swing.JLabel();
		jSeparator26 = new javax.swing.JSeparator();
		jPanel38 = new javax.swing.JPanel();
		jLabel26 = new javax.swing.JLabel();
		jPanel12 = new javax.swing.JPanel();
		jPanel44 = new javax.swing.JPanel();
		size = new javax.swing.JLabel();
		jSeparator27 = new javax.swing.JSeparator();
		jPanel43 = new javax.swing.JPanel();
		jLabel27 = new javax.swing.JLabel();
		jPanel42 = new javax.swing.JPanel();
		gender = new javax.swing.JLabel();
		jSeparator28 = new javax.swing.JSeparator();
		jPanel41 = new javax.swing.JPanel();
		jLabel28 = new javax.swing.JLabel();
		jPanel4 = new javax.swing.JPanel();
		jPanel13 = new javax.swing.JPanel();
		jPanel25 = new javax.swing.JPanel();
		deity = new javax.swing.JLabel();
		jSeparator24 = new javax.swing.JSeparator();
		jPanel26 = new javax.swing.JPanel();
		jLabel29 = new javax.swing.JLabel();
		jPanel15 = new javax.swing.JPanel();
		jPanel16 = new javax.swing.JPanel();
		jPanel45 = new javax.swing.JPanel();
		height = new javax.swing.JLabel();
		jSeparator30 = new javax.swing.JSeparator();
		jPanel46 = new javax.swing.JPanel();
		jLabel30 = new javax.swing.JLabel();
		jPanel47 = new javax.swing.JPanel();
		eyes = new javax.swing.JLabel();
		jSeparator31 = new javax.swing.JSeparator();
		jPanel48 = new javax.swing.JPanel();
		jLabel31 = new javax.swing.JLabel();
		jPanel17 = new javax.swing.JPanel();
		jPanel49 = new javax.swing.JPanel();
		weight = new javax.swing.JLabel();
		jSeparator32 = new javax.swing.JSeparator();
		jPanel50 = new javax.swing.JPanel();
		jLabel32 = new javax.swing.JLabel();
		jPanel51 = new javax.swing.JPanel();
		hair = new javax.swing.JLabel();
		jSeparator33 = new javax.swing.JSeparator();
		jPanel52 = new javax.swing.JPanel();
		jLabel33 = new javax.swing.JLabel();
		jPanel14 = new javax.swing.JPanel();
		jPanel18 = new javax.swing.JPanel();
		jPanel28 = new javax.swing.JPanel();
		alignment = new javax.swing.JLabel();
		jSeparator34 = new javax.swing.JSeparator();
		jPanel27 = new javax.swing.JPanel();
		jLabel34 = new javax.swing.JLabel();
		jPanel20 = new javax.swing.JPanel();
		jPanel19 = new javax.swing.JPanel();
		jPanel53 = new javax.swing.JPanel();
		vision = new javax.swing.JLabel();
		jSeparator35 = new javax.swing.JSeparator();
		jPanel54 = new javax.swing.JPanel();
		jLabel35 = new javax.swing.JLabel();
		jPanel55 = new javax.swing.JPanel();
		points = new javax.swing.JLabel();
		jSeparator36 = new javax.swing.JSeparator();
		jPanel56 = new javax.swing.JPanel();
		jLabel36 = new javax.swing.JLabel();

		setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

		jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

		jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

		jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

		jPanel21.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 1));

		name.setFont(new java.awt.Font("Dialog", 1, 16));
		name.setText(" ");
		jPanel21.add(name);

		jPanel5.add(jPanel21);

		jPanel5.add(jSeparator19);

		jPanel22.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

		jLabel1.setFont(new java.awt.Font("Dialog", 0, 10));
		jLabel1.setText("Name");
		jPanel22.add(jLabel1);

		jPanel5.add(jPanel22);

		jPanel2.add(jPanel5);

		jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.X_AXIS));

		jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.Y_AXIS));

		jPanel32.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

		playerClass.setFont(new java.awt.Font("Dialog", 0, 14));
		playerClass.setText(" ");
		jPanel32.add(playerClass);

		jPanel7.add(jPanel32);

		jPanel7.add(jSeparator20);

		jPanel29.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

		jLabel20.setFont(new java.awt.Font("Dialog", 0, 10));
		jLabel20.setText("Class");
		jPanel29.add(jLabel20);

		jPanel7.add(jPanel29);

		jPanel30.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

		characterLevel.setFont(new java.awt.Font("Dialog", 0, 14));
		characterLevel.setText(" ");
		jPanel30.add(characterLevel);

		jPanel7.add(jPanel30);

		jPanel7.add(jSeparator21);

		jPanel31.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

		jLabel21.setFont(new java.awt.Font("Dialog", 0, 10));
		jLabel21.setText("TCL");
		jPanel31.add(jLabel21);

		jPanel7.add(jPanel31);

		jPanel6.add(jPanel7);

		jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.Y_AXIS));

		jPanel36.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

		experience.setFont(new java.awt.Font("Dialog", 0, 14));
		experience.setText(" ");
		jPanel36.add(experience);

		jPanel8.add(jPanel36);

		jSeparator22.setForeground(CharacterPanel.border);
		jPanel8.add(jSeparator22);

		jPanel34.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

		jLabel22.setFont(new java.awt.Font("Dialog", 0, 10));
		jLabel22.setText("Experience");
		jPanel34.add(jLabel22);

		jPanel8.add(jPanel34);

		jPanel35.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

		nextLevel.setFont(new java.awt.Font("Dialog", 0, 14));
		nextLevel.setText(" ");
		jPanel35.add(nextLevel);

		jPanel8.add(jPanel35);

		jPanel8.add(jSeparator23);

		jPanel33.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

		jLabel23.setFont(new java.awt.Font("Dialog", 0, 10));
		jLabel23.setText("Next Level");
		jPanel33.add(jLabel23);

		jPanel8.add(jPanel33);

		jPanel6.add(jPanel8);

		jPanel2.add(jPanel6);

		jPanel1.add(jPanel2);

		jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

		jPanel3.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 0, 0, 0)));
		jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.Y_AXIS));

		jPanel23.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 2));

		playerName.setFont(new java.awt.Font("Dialog", 0, 13));
		playerName.setText(" ");
		jPanel23.add(playerName);

		jPanel9.add(jPanel23);

		jPanel9.add(jSeparator29);

		jPanel24.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

		jLabel24.setFont(new java.awt.Font("Dialog", 0, 10));
		jLabel24.setText("Player Name");
		jPanel24.add(jLabel24);

		jPanel9.add(jPanel24);

		jPanel3.add(jPanel9);

		jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.X_AXIS));

		jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.Y_AXIS));

		jPanel40.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

		race.setFont(new java.awt.Font("Dialog", 0, 14));
		race.setText(" ");
		jPanel40.add(race);

		jPanel11.add(jPanel40);

		jPanel11.add(jSeparator25);

		jPanel39.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

		jLabel25.setFont(new java.awt.Font("Dialog", 0, 10));
		jLabel25.setText("Race");
		jPanel39.add(jLabel25);

		jPanel11.add(jPanel39);

		jPanel37.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

		age.setFont(new java.awt.Font("Dialog", 0, 14));
		age.setText(" ");
		jPanel37.add(age);

		jPanel11.add(jPanel37);

		jPanel11.add(jSeparator26);

		jPanel38.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

		jLabel26.setFont(new java.awt.Font("Dialog", 0, 10));
		jLabel26.setText("Age");
		jPanel38.add(jLabel26);

		jPanel11.add(jPanel38);

		jPanel10.add(jPanel11);

		jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.Y_AXIS));

		jPanel44.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

		size.setFont(new java.awt.Font("Dialog", 0, 14));
		size.setText(" ");
		jPanel44.add(size);

		jPanel12.add(jPanel44);

		jPanel12.add(jSeparator27);

		jPanel43.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

		jLabel27.setFont(new java.awt.Font("Dialog", 0, 10));
		jLabel27.setText("Size");
		jPanel43.add(jLabel27);

		jPanel12.add(jPanel43);

		jPanel42.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

		gender.setFont(new java.awt.Font("Dialog", 0, 14));
		gender.setText(" ");
		jPanel42.add(gender);

		jPanel12.add(jPanel42);

		jPanel12.add(jSeparator28);

		jPanel41.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

		jLabel28.setFont(new java.awt.Font("Dialog", 0, 10));
		jLabel28.setText("Gender");
		jPanel41.add(jLabel28);

		jPanel12.add(jPanel41);

		jPanel10.add(jPanel12);

		jPanel3.add(jPanel10);

		jPanel1.add(jPanel3);

		jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

		jPanel4.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 0, 0, 0)));
		jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.Y_AXIS));

		jPanel25.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 2));

		deity.setFont(new java.awt.Font("Dialog", 0, 13));
		deity.setText(" ");
		jPanel25.add(deity);

		jPanel13.add(jPanel25);

		jPanel13.add(jSeparator24);

		jPanel26.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

		jLabel29.setFont(new java.awt.Font("Dialog", 0, 10));
		jLabel29.setText("Deity");
		jPanel26.add(jLabel29);

		jPanel13.add(jPanel26);

		jPanel4.add(jPanel13);

		jPanel15.setLayout(new javax.swing.BoxLayout(jPanel15, javax.swing.BoxLayout.X_AXIS));

		jPanel16.setLayout(new javax.swing.BoxLayout(jPanel16, javax.swing.BoxLayout.Y_AXIS));

		jPanel45.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

		height.setFont(new java.awt.Font("Dialog", 0, 14));
		height.setText(" ");
		jPanel45.add(height);

		jPanel16.add(jPanel45);

		jPanel16.add(jSeparator30);

		jPanel46.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

		jLabel30.setFont(new java.awt.Font("Dialog", 0, 10));
		jLabel30.setText("Height");
		jPanel46.add(jLabel30);

		jPanel16.add(jPanel46);

		jPanel47.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

		eyes.setFont(new java.awt.Font("Dialog", 0, 14));
		eyes.setText(" ");
		jPanel47.add(eyes);

		jPanel16.add(jPanel47);

		jPanel16.add(jSeparator31);

		jPanel48.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

		jLabel31.setFont(new java.awt.Font("Dialog", 0, 10));
		jLabel31.setText("Eyes");
		jPanel48.add(jLabel31);

		jPanel16.add(jPanel48);

		jPanel15.add(jPanel16);

		jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.Y_AXIS));

		jPanel49.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

		weight.setFont(new java.awt.Font("Dialog", 0, 14));
		weight.setText(" ");
		jPanel49.add(weight);

		jPanel17.add(jPanel49);

		jPanel17.add(jSeparator32);

		jPanel50.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

		jLabel32.setFont(new java.awt.Font("Dialog", 0, 10));
		jLabel32.setText("Weight");
		jPanel50.add(jLabel32);

		jPanel17.add(jPanel50);

		jPanel51.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

		hair.setFont(new java.awt.Font("Dialog", 0, 14));
		hair.setText(" ");
		jPanel51.add(hair);

		jPanel17.add(jPanel51);

		jPanel17.add(jSeparator33);

		jPanel52.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

		jLabel33.setFont(new java.awt.Font("Dialog", 0, 10));
		jLabel33.setText("Hair");
		jPanel52.add(jLabel33);

		jPanel17.add(jPanel52);

		jPanel15.add(jPanel17);

		jPanel4.add(jPanel15);

		jPanel1.add(jPanel4);

		jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.Y_AXIS));

		jPanel14.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 0, 0, 0)));
		jPanel18.setLayout(new javax.swing.BoxLayout(jPanel18, javax.swing.BoxLayout.Y_AXIS));

		jPanel28.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 2));

		alignment.setFont(new java.awt.Font("Dialog", 0, 13));
		alignment.setText(" ");
		jPanel28.add(alignment);

		jPanel18.add(jPanel28);

		jPanel18.add(jSeparator34);

		jPanel27.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

		jLabel34.setFont(new java.awt.Font("Dialog", 0, 10));
		jLabel34.setText("Alignment");
		jPanel27.add(jLabel34);

		jPanel18.add(jPanel27);

		jPanel14.add(jPanel18);

		jPanel20.setLayout(new javax.swing.BoxLayout(jPanel20, javax.swing.BoxLayout.X_AXIS));

		jPanel19.setLayout(new javax.swing.BoxLayout(jPanel19, javax.swing.BoxLayout.Y_AXIS));

		jPanel53.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

		vision.setFont(new java.awt.Font("Dialog", 0, 14));
		vision.setText(" ");
		jPanel53.add(vision);

		jPanel19.add(jPanel53);

		jPanel19.add(jSeparator35);

		jPanel54.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

		jLabel35.setFont(new java.awt.Font("Dialog", 0, 10));
		jLabel35.setText("Vision");
		jPanel54.add(jLabel35);

		jPanel19.add(jPanel54);

		jPanel55.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

		points.setFont(new java.awt.Font("Dialog", 0, 14));
		points.setText(" ");
		jPanel55.add(points);

		jPanel19.add(jPanel55);

		jPanel19.add(jSeparator36);

		jPanel56.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

		jLabel36.setFont(new java.awt.Font("Dialog", 0, 10));
		jLabel36.setText("Points");
		jPanel56.add(jLabel36);

		jPanel19.add(jPanel56);

		jPanel20.add(jPanel19);

		jPanel14.add(jPanel20);

		jPanel1.add(jPanel14);

		add(jPanel1);

	}//GEN-END:initComponents


	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel age;
	private javax.swing.JLabel alignment;
	private javax.swing.JLabel characterLevel;
	private javax.swing.JLabel deity;
	private javax.swing.JLabel experience;
	private javax.swing.JLabel eyes;
	private javax.swing.JLabel gender;
	private javax.swing.JLabel hair;
	private javax.swing.JLabel height;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel22;
	private javax.swing.JLabel jLabel23;
	private javax.swing.JLabel jLabel24;
	private javax.swing.JLabel jLabel25;
	private javax.swing.JLabel jLabel26;
	private javax.swing.JLabel jLabel27;
	private javax.swing.JLabel jLabel28;
	private javax.swing.JLabel jLabel29;
	private javax.swing.JLabel jLabel30;
	private javax.swing.JLabel jLabel31;
	private javax.swing.JLabel jLabel32;
	private javax.swing.JLabel jLabel33;
	private javax.swing.JLabel jLabel34;
	private javax.swing.JLabel jLabel35;
	private javax.swing.JLabel jLabel36;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel10;
	private javax.swing.JPanel jPanel11;
	private javax.swing.JPanel jPanel12;
	private javax.swing.JPanel jPanel13;
	private javax.swing.JPanel jPanel14;
	private javax.swing.JPanel jPanel15;
	private javax.swing.JPanel jPanel16;
	private javax.swing.JPanel jPanel17;
	private javax.swing.JPanel jPanel18;
	private javax.swing.JPanel jPanel19;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel20;
	private javax.swing.JPanel jPanel21;
	private javax.swing.JPanel jPanel22;
	private javax.swing.JPanel jPanel23;
	private javax.swing.JPanel jPanel24;
	private javax.swing.JPanel jPanel25;
	private javax.swing.JPanel jPanel26;
	private javax.swing.JPanel jPanel27;
	private javax.swing.JPanel jPanel28;
	private javax.swing.JPanel jPanel29;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel30;
	private javax.swing.JPanel jPanel31;
	private javax.swing.JPanel jPanel32;
	private javax.swing.JPanel jPanel33;
	private javax.swing.JPanel jPanel34;
	private javax.swing.JPanel jPanel35;
	private javax.swing.JPanel jPanel36;
	private javax.swing.JPanel jPanel37;
	private javax.swing.JPanel jPanel38;
	private javax.swing.JPanel jPanel39;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel40;
	private javax.swing.JPanel jPanel41;
	private javax.swing.JPanel jPanel42;
	private javax.swing.JPanel jPanel43;
	private javax.swing.JPanel jPanel44;
	private javax.swing.JPanel jPanel45;
	private javax.swing.JPanel jPanel46;
	private javax.swing.JPanel jPanel47;
	private javax.swing.JPanel jPanel48;
	private javax.swing.JPanel jPanel49;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel50;
	private javax.swing.JPanel jPanel51;
	private javax.swing.JPanel jPanel52;
	private javax.swing.JPanel jPanel53;
	private javax.swing.JPanel jPanel54;
	private javax.swing.JPanel jPanel55;
	private javax.swing.JPanel jPanel56;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPanel jPanel8;
	private javax.swing.JPanel jPanel9;
	private javax.swing.JSeparator jSeparator19;
	private javax.swing.JSeparator jSeparator20;
	private javax.swing.JSeparator jSeparator21;
	private javax.swing.JSeparator jSeparator22;
	private javax.swing.JSeparator jSeparator23;
	private javax.swing.JSeparator jSeparator24;
	private javax.swing.JSeparator jSeparator25;
	private javax.swing.JSeparator jSeparator26;
	private javax.swing.JSeparator jSeparator27;
	private javax.swing.JSeparator jSeparator28;
	private javax.swing.JSeparator jSeparator29;
	private javax.swing.JSeparator jSeparator30;
	private javax.swing.JSeparator jSeparator31;
	private javax.swing.JSeparator jSeparator32;
	private javax.swing.JSeparator jSeparator33;
	private javax.swing.JSeparator jSeparator34;
	private javax.swing.JSeparator jSeparator35;
	private javax.swing.JSeparator jSeparator36;
	private javax.swing.JLabel name;
	private javax.swing.JLabel nextLevel;
	private javax.swing.JLabel playerClass;
	private javax.swing.JLabel playerName;
	private javax.swing.JLabel points;
	private javax.swing.JLabel race;
	private javax.swing.JLabel size;
	private javax.swing.JLabel vision;
	private javax.swing.JLabel weight;
	// End of variables declaration//GEN-END:variables

	private static final String SPACE = " ";
	
	/**
	 * setColor
	 */
	public void setColor() {
		setBackground(CharacterPanel.white);
		jPanel1.setBackground(CharacterPanel.white);
		jPanel2.setBackground(CharacterPanel.white);
		jPanel3.setBackground(CharacterPanel.white);
		jPanel4.setBackground(CharacterPanel.white);
		jPanel5.setBackground(CharacterPanel.white);
		jPanel6.setBackground(CharacterPanel.white);
		jPanel7.setBackground(CharacterPanel.white);
		jPanel8.setBackground(CharacterPanel.white);
		jPanel9.setBackground(CharacterPanel.white);
		jPanel10.setBackground(CharacterPanel.white);
		jPanel11.setBackground(CharacterPanel.white);
		jPanel12.setBackground(CharacterPanel.white);
		jPanel13.setBackground(CharacterPanel.white);
		jPanel14.setBackground(CharacterPanel.white);
		jPanel15.setBackground(CharacterPanel.white);
		jPanel16.setBackground(CharacterPanel.white);
		jPanel18.setBackground(CharacterPanel.white);
		jPanel19.setBackground(CharacterPanel.white);
		jPanel20.setBackground(CharacterPanel.white);
		jPanel21.setBackground(CharacterPanel.white);
		jPanel22.setBackground(CharacterPanel.white);
		jPanel23.setBackground(CharacterPanel.white);
		jPanel24.setBackground(CharacterPanel.white);
		jPanel25.setBackground(CharacterPanel.white);
		jPanel26.setBackground(CharacterPanel.white);
		jPanel27.setBackground(CharacterPanel.white);
		jPanel28.setBackground(CharacterPanel.white);
		jPanel29.setBackground(CharacterPanel.white);
		jPanel30.setBackground(CharacterPanel.white);
		jPanel31.setBackground(CharacterPanel.white);
		jPanel32.setBackground(CharacterPanel.white);
		jPanel33.setBackground(CharacterPanel.white);
		jPanel34.setBackground(CharacterPanel.white);
		jPanel35.setBackground(CharacterPanel.white);
		jPanel36.setBackground(CharacterPanel.white);
		jPanel37.setBackground(CharacterPanel.white);
		jPanel38.setBackground(CharacterPanel.white);
		jPanel39.setBackground(CharacterPanel.white);
		jPanel40.setBackground(CharacterPanel.white);
		jPanel41.setBackground(CharacterPanel.white);
		jPanel42.setBackground(CharacterPanel.white);
		jPanel43.setBackground(CharacterPanel.white);
		jPanel44.setBackground(CharacterPanel.white);
		jPanel45.setBackground(CharacterPanel.white);
		jPanel46.setBackground(CharacterPanel.white);
		jPanel47.setBackground(CharacterPanel.white);
		jPanel48.setBackground(CharacterPanel.white);
		jPanel49.setBackground(CharacterPanel.white);
		jPanel50.setBackground(CharacterPanel.white);
		jPanel51.setBackground(CharacterPanel.white);
		jPanel52.setBackground(CharacterPanel.white);
		jPanel53.setBackground(CharacterPanel.white);
		jPanel54.setBackground(CharacterPanel.white);
		jPanel55.setBackground(CharacterPanel.white);
		jPanel56.setBackground(CharacterPanel.white);
		jSeparator19.setBackground(CharacterPanel.white);
		jSeparator19.setForeground(CharacterPanel.border);
		jSeparator20.setBackground(CharacterPanel.white);
		jSeparator20.setForeground(CharacterPanel.border);
		jSeparator21.setBackground(CharacterPanel.white);
		jSeparator21.setForeground(CharacterPanel.border);
		jSeparator22.setBackground(CharacterPanel.white);
		jSeparator22.setForeground(CharacterPanel.border);
		jSeparator23.setBackground(CharacterPanel.white);
		jSeparator23.setForeground(CharacterPanel.border);
		jSeparator24.setBackground(CharacterPanel.white);
		jSeparator24.setForeground(CharacterPanel.border);
		jSeparator25.setBackground(CharacterPanel.white);
		jSeparator25.setForeground(CharacterPanel.border);
		jSeparator26.setBackground(CharacterPanel.white);
		jSeparator26.setForeground(CharacterPanel.border);
		jSeparator27.setBackground(CharacterPanel.white);
		jSeparator27.setForeground(CharacterPanel.border);
		jSeparator28.setBackground(CharacterPanel.white);
		jSeparator28.setForeground(CharacterPanel.border);
		jSeparator29.setBackground(CharacterPanel.white);
		jSeparator29.setForeground(CharacterPanel.border);
		jSeparator30.setBackground(CharacterPanel.white);
		jSeparator30.setForeground(CharacterPanel.border);
		jSeparator31.setBackground(CharacterPanel.white);
		jSeparator31.setForeground(CharacterPanel.border);
		jSeparator32.setBackground(CharacterPanel.white);
		jSeparator32.setForeground(CharacterPanel.border);
		jSeparator33.setBackground(CharacterPanel.white);
		jSeparator33.setForeground(CharacterPanel.border);
		jSeparator34.setBackground(CharacterPanel.white);
		jSeparator34.setForeground(CharacterPanel.border);
		jSeparator35.setBackground(CharacterPanel.white);
		jSeparator35.setForeground(CharacterPanel.border);
		jSeparator36.setBackground(CharacterPanel.white);
		jSeparator36.setForeground(CharacterPanel.border);
	}

	/**
	 * Set PC
	 * @param pc
	 */
	public void setPc(PlayerCharacter pc) {
		this.pc = pc;
	}

	/**
	 * Refresh
	 */
	public void refresh() {
		new PlayerCharacterOutput(pc);

		name.setText(pc.getName() + ' ');
		playerClass.setText(getClasses(pc) + ' ');
		characterLevel.setText(pc.getECL() + SPACE);
		experience.setText(pc.getXP() + SPACE);
		nextLevel.setText(pc.minXPForNextECL() + " ");

		playerName.setText(pc.getPlayersName() + ' ');
		if (pc.getSubRace().equals(Constants.s_NONE))
		{
			race.setText(pc.getRace().getName() + ' ');
		}
		else
		{
			race.setText(pc.getRace().getName() + " (" + pc.getSubRace() + ") ");
		}
		age.setText(pc.getAge() + " ");
		size.setText(SizeLongToken.getSizeLongToken(pc) + ' ');
		gender.setText(pc.getGender() + ' ');

		if (pc.getDeity() != null) {
			deity.setText(pc.getDeity().getName() + ' ');
		}
		height.setText(HeightToken.getHeightToken(pc) + ' ');
		eyes.setText(pc.getEyeColor() + ' ');
		weight.setText(WeightToken.getWeightToken(pc) + ' ');
		hair.setText(pc.getHairColor() + ' ');

		alignment.setText(AlignmentToken.getAlignmentToken(pc) + ' ');
		vision.setText(pc.getVision() + ' ');
		points.setText(pc.getCostPool() + SPACE);
	}

	private String getClasses(PlayerCharacter aPC) {
		StringBuffer sb = new StringBuffer();
		ArrayList classList = aPC.getClassList();

		for (int i = 0; i < classList.size(); i++) {
			PCClass mClass = (PCClass) classList.get(i);
			sb.append(mClass.getAbbrev()).append(mClass.getLevel()).append(' ');
		}

		return sb.toString();
	}

	/**
	 * Destruct
	 */
	public void destruct() {
		//Put any code here that is needed to prevent memory leaks when this panel is destroyed
	}
}
