/*
 * RangedWeaponPane.java
 *
 * Created on February 3, 2004, 3:23 PM
 */

package plugin.charactersheet.gui;

import gmgen.plugin.PlayerCharacterOutput;
import pcgen.core.Equipment;
import pcgen.core.PlayerCharacter;
import pcgen.io.exporttoken.WeaponToken;

/**
 *
 * @author  ddjone3
 */
public class RangedWeaponPane extends javax.swing.JPanel {
	private PlayerCharacter pc;
	private Equipment eq;

	/** Creates new form RangedWeaponPane */
	public RangedWeaponPane() {
		initComponents();
		setColor();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents() {//GEN-BEGIN:initComponents
		jPanel13 = new javax.swing.JPanel();
		jPanel14 = new javax.swing.JPanel();
		jPanel22 = new javax.swing.JPanel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jPanel21 = new javax.swing.JPanel();
		jLabel8 = new javax.swing.JLabel();
		jPanel24 = new javax.swing.JPanel();
		jLabel9 = new javax.swing.JLabel();
		jPanel15 = new javax.swing.JPanel();
		jPanel23 = new javax.swing.JPanel();
		jPanelAmmo = new javax.swing.JPanel();
		ammoLabel = new javax.swing.JLabel();
		ammo = new javax.swing.JLabel();
		range1 = new javax.swing.JLabel();
		jPanel12 = new javax.swing.JPanel();
		range1ToHit = new javax.swing.JLabel();
		jPanel16 = new javax.swing.JPanel();
		range1Damage = new javax.swing.JLabel();
		jPanel20 = new javax.swing.JPanel();
		jPanel25 = new javax.swing.JPanel();
		range2 = new javax.swing.JLabel();
		jPanel29 = new javax.swing.JPanel();
		range2ToHit = new javax.swing.JLabel();
		jPanel30 = new javax.swing.JPanel();
		range2Damage = new javax.swing.JLabel();
		jPanel19 = new javax.swing.JPanel();
		jPanel26 = new javax.swing.JPanel();
		range3 = new javax.swing.JLabel();
		jPanel32 = new javax.swing.JPanel();
		range3ToHit = new javax.swing.JLabel();
		jPanel31 = new javax.swing.JPanel();
		range3Damage = new javax.swing.JLabel();
		jPanel18 = new javax.swing.JPanel();
		jPanel27 = new javax.swing.JPanel();
		range4 = new javax.swing.JLabel();
		jPanel34 = new javax.swing.JPanel();
		range4ToHit = new javax.swing.JLabel();
		jPanel33 = new javax.swing.JPanel();
		range4Damage = new javax.swing.JLabel();
		jPanel17 = new javax.swing.JPanel();
		jPanel28 = new javax.swing.JPanel();
		range5 = new javax.swing.JLabel();
		jPanel36 = new javax.swing.JPanel();
		range5ToHit = new javax.swing.JLabel();
		jPanel35 = new javax.swing.JPanel();
		range5Damage = new javax.swing.JLabel();

		setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

		jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.X_AXIS));

		jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.Y_AXIS));

		jPanel22.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 1, 0));

		jPanel22.add(jLabel10);

		jPanelAmmo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 1, 0));

		ammoLabel.setFont(new java.awt.Font("Dialog", 0, 10));
		ammoLabel.setText("Ammunition:");
		jPanelAmmo.add(ammoLabel);
		ammo.setFont(new java.awt.Font("Dialog", 0, 10));
		ammo.setText("None");
		jPanelAmmo.add(ammo);
		add(jPanelAmmo);

		jLabel11.setFont(new java.awt.Font("Dialog", 1, 10));
		jLabel11.setText(" ");
		jPanel22.add(jLabel11);

		jPanel14.add(jPanel22);

		jPanel21.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 1, 0));

		jLabel8.setFont(new java.awt.Font("Dialog", 0, 10));
		jLabel8.setText("To Hit");
		jPanel21.add(jLabel8);

		jPanel14.add(jPanel21);

		jPanel24.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 1, 0));

		jLabel9.setFont(new java.awt.Font("Dialog", 0, 10));
		jLabel9.setText("Dam");
		jPanel24.add(jLabel9);

		jPanel14.add(jPanel24);

		jPanel13.add(jPanel14);

		jPanel15.setLayout(new javax.swing.BoxLayout(jPanel15, javax.swing.BoxLayout.Y_AXIS));

		jPanel23.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 1, 0));

		range1.setFont(new java.awt.Font("Dialog", 0, 10));
		range1.setText(" ");
		jPanel23.add(range1);

		jPanel15.add(jPanel23);

		jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 1, 0));

		range1ToHit.setFont(new java.awt.Font("Dialog", 0, 10));
		range1ToHit.setText(" ");
		jPanel12.add(range1ToHit);

		jPanel15.add(jPanel12);

		jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 1, 0));

		range1Damage.setFont(new java.awt.Font("Dialog", 0, 10));
		range1Damage.setText(" ");
		jPanel16.add(range1Damage);

		jPanel15.add(jPanel16);

		jPanel13.add(jPanel15);

		jPanel20.setLayout(new javax.swing.BoxLayout(jPanel20, javax.swing.BoxLayout.Y_AXIS));

		jPanel25.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 1, 0));

		range2.setFont(new java.awt.Font("Dialog", 0, 10));
		range2.setText(" ");
		jPanel25.add(range2);

		jPanel20.add(jPanel25);

		jPanel29.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 1, 0));

		range2ToHit.setFont(new java.awt.Font("Dialog", 0, 10));
		range2ToHit.setText(" ");
		jPanel29.add(range2ToHit);

		jPanel20.add(jPanel29);

		jPanel30.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 1, 0));

		range2Damage.setFont(new java.awt.Font("Dialog", 0, 10));
		range2Damage.setText(" ");
		jPanel30.add(range2Damage);

		jPanel20.add(jPanel30);

		jPanel13.add(jPanel20);

		jPanel19.setLayout(new javax.swing.BoxLayout(jPanel19, javax.swing.BoxLayout.Y_AXIS));

		jPanel26.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 1, 0));

		range3.setFont(new java.awt.Font("Dialog", 0, 10));
		range3.setText(" ");
		jPanel26.add(range3);

		jPanel19.add(jPanel26);

		jPanel32.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 1, 0));

		range3ToHit.setFont(new java.awt.Font("Dialog", 0, 10));
		range3ToHit.setText(" ");
		jPanel32.add(range3ToHit);

		jPanel19.add(jPanel32);

		jPanel31.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 1, 0));

		range3Damage.setFont(new java.awt.Font("Dialog", 0, 10));
		range3Damage.setText(" ");
		jPanel31.add(range3Damage);

		jPanel19.add(jPanel31);

		jPanel13.add(jPanel19);

		jPanel18.setLayout(new javax.swing.BoxLayout(jPanel18, javax.swing.BoxLayout.Y_AXIS));

		jPanel27.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 1, 0));

		range4.setFont(new java.awt.Font("Dialog", 0, 10));
		range4.setText(" ");
		jPanel27.add(range4);

		jPanel18.add(jPanel27);

		jPanel34.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 1, 0));

		range4ToHit.setFont(new java.awt.Font("Dialog", 0, 10));
		range4ToHit.setText(" ");
		jPanel34.add(range4ToHit);

		jPanel18.add(jPanel34);

		jPanel33.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 1, 0));

		range4Damage.setFont(new java.awt.Font("Dialog", 0, 10));
		range4Damage.setText(" ");
		jPanel33.add(range4Damage);

		jPanel18.add(jPanel33);

		jPanel13.add(jPanel18);

		jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.Y_AXIS));

		jPanel28.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 1, 0));

		range5.setFont(new java.awt.Font("Dialog", 0, 10));
		range5.setText(" ");
		jPanel28.add(range5);

		jPanel17.add(jPanel28);

		jPanel36.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 1, 0));

		range5ToHit.setFont(new java.awt.Font("Dialog", 0, 10));
		range5ToHit.setText(" ");
		jPanel36.add(range5ToHit);

		jPanel17.add(jPanel36);

		jPanel35.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 1, 0));

		range5Damage.setFont(new java.awt.Font("Dialog", 0, 10));
		range5Damage.setText(" ");
		jPanel35.add(range5Damage);

		jPanel17.add(jPanel35);

		jPanel13.add(jPanel17);

		add(jPanel13);

	}//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel12;
	private javax.swing.JPanel jPanel13;
	private javax.swing.JPanel jPanel14;
	private javax.swing.JPanel jPanel15;
	private javax.swing.JPanel jPanel16;
	private javax.swing.JPanel jPanel17;
	private javax.swing.JPanel jPanel18;
	private javax.swing.JPanel jPanel19;
	private javax.swing.JPanel jPanel20;
	private javax.swing.JPanel jPanel21;
	private javax.swing.JPanel jPanel22;
	private javax.swing.JPanel jPanel23;
	private javax.swing.JPanel jPanel24;
	private javax.swing.JPanel jPanel25;
	private javax.swing.JPanel jPanel26;
	private javax.swing.JPanel jPanel27;
	private javax.swing.JPanel jPanel28;
	private javax.swing.JPanel jPanel29;
	private javax.swing.JPanel jPanel30;
	private javax.swing.JPanel jPanel31;
	private javax.swing.JPanel jPanel32;
	private javax.swing.JPanel jPanel33;
	private javax.swing.JPanel jPanel34;
	private javax.swing.JPanel jPanel35;
	private javax.swing.JPanel jPanel36;
	private javax.swing.JPanel jPanelAmmo;
	private javax.swing.JLabel ammoLabel;
	private javax.swing.JLabel ammo;
	private javax.swing.JLabel range1;
	private javax.swing.JLabel range1Damage;
	private javax.swing.JLabel range1ToHit;
	private javax.swing.JLabel range2;
	private javax.swing.JLabel range2Damage;
	private javax.swing.JLabel range2ToHit;
	private javax.swing.JLabel range3;
	private javax.swing.JLabel range3Damage;
	private javax.swing.JLabel range3ToHit;
	private javax.swing.JLabel range4;
	private javax.swing.JLabel range4Damage;
	private javax.swing.JLabel range4ToHit;
	private javax.swing.JLabel range5;
	private javax.swing.JLabel range5Damage;
	private javax.swing.JLabel range5ToHit;
	// End of variables declaration//GEN-END:variables

	/** 
	 * Set the color of the pane
	 */
	public void setColor() {
		setBackground(CharacterPanel.border);
		setBorder(new javax.swing.border.LineBorder(CharacterPanel.border));
		jPanel13.setBackground(CharacterPanel.border);
		jPanel14.setBackground(CharacterPanel.border);
		jPanel22.setBackground(CharacterPanel.header);
		jPanel22.setBorder(new javax.swing.border.LineBorder(CharacterPanel.border));
		jPanel21.setBackground(CharacterPanel.header);
		jPanel21.setBorder(new javax.swing.border.LineBorder(CharacterPanel.border));
		jPanel24.setBackground(CharacterPanel.header);
		jPanel24.setBorder(new javax.swing.border.LineBorder(CharacterPanel.border));
		jPanel15.setBackground(CharacterPanel.border);
		jPanel23.setBackground(CharacterPanel.header);
		jPanel23.setBorder(new javax.swing.border.LineBorder(CharacterPanel.border));
		jPanelAmmo.setBackground(CharacterPanel.header);
		jPanelAmmo.setBorder(new javax.swing.border.LineBorder(CharacterPanel.border));
		jPanel12.setBackground(CharacterPanel.bodyLight);
		jPanel12.setBorder(new javax.swing.border.LineBorder(CharacterPanel.border));
		jPanel16.setBackground(CharacterPanel.bodyLight);
		jPanel16.setBorder(new javax.swing.border.LineBorder(CharacterPanel.border));
		jPanel20.setBackground(CharacterPanel.border);
		jPanel25.setBackground(CharacterPanel.header);
		jPanel25.setBorder(new javax.swing.border.LineBorder(CharacterPanel.border));
		jPanel29.setBackground(CharacterPanel.bodyLight);
		jPanel29.setBorder(new javax.swing.border.LineBorder(CharacterPanel.border));
		jPanel30.setBackground(CharacterPanel.bodyLight);
		jPanel30.setBorder(new javax.swing.border.LineBorder(CharacterPanel.border));
		jPanel19.setBackground(CharacterPanel.border);
		jPanel26.setBackground(CharacterPanel.header);
		jPanel26.setBorder(new javax.swing.border.LineBorder(CharacterPanel.border));
		jPanel32.setBackground(CharacterPanel.bodyLight);
		jPanel32.setBorder(new javax.swing.border.LineBorder(CharacterPanel.border));
		jPanel31.setBackground(CharacterPanel.bodyLight);
		jPanel31.setBorder(new javax.swing.border.LineBorder(CharacterPanel.border));
		jPanel18.setBackground(CharacterPanel.border);
		jPanel27.setBackground(CharacterPanel.header);
		jPanel27.setBorder(new javax.swing.border.LineBorder(CharacterPanel.border));
		jPanel34.setBackground(CharacterPanel.bodyLight);
		jPanel34.setBorder(new javax.swing.border.LineBorder(CharacterPanel.border));
		jPanel33.setBackground(CharacterPanel.bodyLight);
		jPanel33.setBorder(new javax.swing.border.LineBorder(CharacterPanel.border));
		jPanel17.setBackground(CharacterPanel.border);
		jPanel28.setBackground(CharacterPanel.header);
		jPanel28.setBorder(new javax.swing.border.LineBorder(CharacterPanel.border));
		jPanel36.setBackground(CharacterPanel.bodyLight);
		jPanel36.setBorder(new javax.swing.border.LineBorder(CharacterPanel.border));
		jPanel35.setBackground(CharacterPanel.bodyLight);
		jPanel35.setBorder(new javax.swing.border.LineBorder(CharacterPanel.border));
	}

	/**
	 * Set the weapon on the PC and refresh the pane
	 * @param pc
	 * @param eq
	 */
	public void setWeapon(PlayerCharacter pc, Equipment eq) {
		this.pc = pc;
		this.eq = eq;
		refresh();
	}

	/**
	 * Refresh the pane
	 */
	public void refresh() {
		new PlayerCharacterOutput(pc);
		if(eq.isRanged()) {
			range1.setText(WeaponToken.getRangeListToken(eq, 0, pc));
			range2.setText(WeaponToken.getRangeListToken(eq, 1, pc));
			range3.setText(WeaponToken.getRangeListToken(eq, 2, pc));
			range4.setText(WeaponToken.getRangeListToken(eq, 3, pc));
			range5.setText(WeaponToken.getRangeListToken(eq, 4, pc));

			String ammoVal = WeaponToken.getContentsToken(eq, 0);
			if (ammoVal != null && ammoVal.length() > 0)
			{
				ammo.setText(ammoVal);
				jPanelAmmo.setVisible(true);
			}
			else
			{
				ammo.setText("None");
				jPanelAmmo.setVisible(false);
			}
			
			range1Damage.setText(WeaponToken.getDamageToken(pc, eq, 0, 0, -1, false, false));
			range2Damage.setText(WeaponToken.getDamageToken(pc, eq, 1, 0, -1, false, false));
			range3Damage.setText(WeaponToken.getDamageToken(pc, eq, 2, 0, -1, false, false));
			range4Damage.setText(WeaponToken.getDamageToken(pc, eq, 3, 0, -1, false, false));
			range5Damage.setText(WeaponToken.getDamageToken(pc, eq, 4, 0, -1, false, false));

			range1ToHit.setText(WeaponToken.getTotalHitToken(pc, eq, 0, 0, -1, -1));
			range2ToHit.setText(WeaponToken.getTotalHitToken(pc, eq, 1, 0, -1, -1));
			range3ToHit.setText(WeaponToken.getTotalHitToken(pc, eq, 2, 0, -1, -1));
			range4ToHit.setText(WeaponToken.getTotalHitToken(pc, eq, 3, 0, -1, -1));
			range5ToHit.setText(WeaponToken.getTotalHitToken(pc, eq, 4, 0, -1, -1));

			this.setVisible(true);
		}
		else {
			this.setVisible(false);
		}
	}
}

