/*
 * SpellPage.java
 *
 * Created on February 26, 2004, 8:44 PM
 */

package plugin.charactersheet.gui;

import gmgen.gui.ScrollablePanel;
import pcgen.core.PCClass;
import pcgen.core.PlayerCharacter;

import java.util.Properties;

/**
 *
 * @author  soulcatcher
 */
public class SpellPage extends ScrollablePanel {
	private ClassSpellLevelPane classSpellLevelPane;

	/**
	 * Creates new form SpellPage
	 * @param scroll
	 */
	public SpellPage(int scroll) {
		super(scroll);
		initComponents();
		setLocalColor();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents() {//GEN-BEGIN:initComponents
		setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
	}

	public void setColor() {
		setLocalColor();
		classSpellLevelPane.setColor();
	}

	public void setLocalColor() {
		setBackground(CharacterPanel.white);
	}

	public void setPc(PlayerCharacter pc, Properties pcProperties, PCClass pcclass, int level) {
		classSpellLevelPane = new ClassSpellLevelPane();
		classSpellLevelPane.setPc(pc, pcclass, level);
		add(classSpellLevelPane);
	}

	public void setPc(PlayerCharacter pc, Properties pcProperties) {

		classSpellLevelPane = new ClassSpellLevelPane();
		classSpellLevelPane.setPc(pc);
		add(classSpellLevelPane);
	}

	public void refresh() {
		if(classSpellLevelPane != null) {
			classSpellLevelPane.refresh();
		}
	}

	public void updateProperties() {
		// TODO - Method does nothing?
	}

	public void destruct() {
		classSpellLevelPane.destruct();
		removeAll();
		classSpellLevelPane = null;
	}
}
