/*
 * UnarmedPane.java
 *
 * Created on February 3, 2004, 3:23 PM
 */

package plugin.charactersheet.gui;

import pcgen.core.Equipment;
import pcgen.core.PlayerCharacter;
import pcgen.io.exporttoken.WeaponToken;

import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import java.awt.Font;

/**
 * <code>WeaponSpecialPane</code>.
 * 
 * @author  ddjone3
 * @version	$Revision$
 */
public class WeaponSpecialPane extends javax.swing.JPanel
{
	private PlayerCharacter pc;
	private Equipment eq;

	private JPanel labelPanel;
	private JPanel propPanel;
	private JTextArea specialProperties;

	private static final String SPROPS = "Special Properties";
	private static final String BLANK = "";
	private static final Font FONT_TEN = new Font("Dialog", 0, 10);

	/** Creates new form UnarmedPane */
	public WeaponSpecialPane()
	{
		initComponents();
		setColor();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents()
	{
		labelPanel = new JPanel();
		propPanel = new JPanel();
		specialProperties = new JTextArea();

		setLayout(new BoxLayout(this, BoxLayout.X_AXIS));

		JLabel sPropsLabel = new JLabel();
		sPropsLabel.setFont(FONT_TEN);
		sPropsLabel.setText(SPROPS);
		labelPanel.add(sPropsLabel);

		add(labelPanel);

		propPanel.setLayout(new BoxLayout(propPanel, BoxLayout.X_AXIS));

		specialProperties.setFont(FONT_TEN);
		specialProperties.setLineWrap(true);
		specialProperties.setWrapStyleWord(true);
		propPanel.add(specialProperties);

		add(propPanel);

	}

	/**
	 * Sets the background and border colour of the WeaponSpecialPane and sub-components.
	 */
	public void setColor()
	{
		setBackground(CharacterPanel.border);
		setBorder(new javax.swing.border.LineBorder(CharacterPanel.border));
		labelPanel.setBackground(CharacterPanel.header);
		labelPanel.setBorder(new javax.swing.border.LineBorder(
			CharacterPanel.border));
		propPanel.setBackground(CharacterPanel.border);
		specialProperties.setBackground(CharacterPanel.bodyLight);
		specialProperties.setBorder(new javax.swing.border.LineBorder(
			CharacterPanel.border));
	}

	/**
	 * Sets the weapon special properties by setting a player character and equipment.
	 * 
	 * @param pc player character to set.
	 * @param eq equipment to set.
	 */
	public void setWeapon(PlayerCharacter pc, Equipment eq)
	{
		this.pc = pc;
		this.eq = eq;
		refresh();
	}

	/**
	 * Refresh the weapon special properties
	 */
	public void refresh()
	{
		String sprop = WeaponToken.getSpropToken(pc, eq).trim();
		if (!sprop.equals(BLANK))
		{
			this.setVisible(true);
			specialProperties.setText(sprop);
		}
		else
		{
			this.setVisible(false);
		}
	}
}
